global using Xunit;
global using SunamoPercentCalculator;
global using SunamoTextOutputGenerator;
global using SunamoValues;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System;
