// EN: Variable names have been checked and replaced with self-descriptive names
// CZ: Názvy proměnných byly zkontrolovány a nahrazeny samopopisnými názvy
global using System.Collections.Generic;
global using System;
global using System.Linq;
global using System.Text;
global using System.Collections;
global using System.Data;
global using System.IO;
global using SunamoCollections._public.SunamoArgs;
global using SunamoCollections._sunamo.SunamoAttributes;
global using SunamoCollections._sunamo.SunamoExtensions;
global using SunamoCollections._sunamo.SunamoPercentCalculator;
global using SunamoCollections._public.SunamoData.Data;
global using SunamoCollections._public.SunamoEnums.Enums;
global using SunamoCollections._sunamo.SunamoExceptions;
global using Diacritics.Extensions;
global using System.Diagnostics;
global using System.Runtime.CompilerServices;
global using System.Text.RegularExpressions;
global using SunamoCollections._sunamo;
global using System.Reflection;
global using System.Net;
global using System.Diagnostics.CodeAnalysis;
global using SunamoCollections;
global using SunamoCollections.Services;
global using SunamoCollections._sunamo.SunamoArgs;
//global using SunamoCollections._sunamo.SunamoParsing;
global using SunamoCollections._sunamo.SunamoTextOutputGenerator;
global using SunamoCollections._sunamo.SunamoValues;
global using SunamoCollections._sunamo.SunamoValues.Constants;
global using System.Threading.Tasks;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
