name: Build SunamoCollections

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoCollections
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollections/SunamoCollections.csproj

    - name: Build
      run: dotnet build SunamoCollections/SunamoCollections.csproj --configuration Release --no-restore

  test:
    name: Test SunamoCollections.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollections.Tests/SunamoCollections.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoCollections.Tests/SunamoCollections.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoCollections.Tests/SunamoCollections.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
